services:
  - type: web
    name: suna-ai-frontend
    env: node
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npm start
    plan: free
    region: oregon
    branch: main
    rootDir: ./
    envVars:
      - key: NEXT_PUBLIC_ENV_MODE
        value: production
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://suna-m91e.onrender.com/api
      - key: NEXT_PUBLIC_URL
        value: https://suna-m91e.onrender.com
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"

  - type: web
    name: suna-ai-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ENV_MODE
        value: production
      - key: PYTHONPATH
        value: /app
      - key: WORKERS
        value: "8"
      - key: PORT
        value: "8000"
      - key: REDIS_HOST
        value: localhost
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_SSL
        value: "false"
      - key: API_KEY_SECRET
        value: "render-production-secret-key-2024"
      - key: MCP_CREDENTIAL_ENCRYPTION_KEY
        value: "render-mcp-encryption-key-2024"
    disk:
      name: suna-data
      mountPath: /data
      sizeGB: 1