[build]
# Use Dockerfile for building
builder = "dockerfile"

[deploy]
# Start command for the FastAPI application
startCommand = "python simple_server.py"

# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 300

# Environment configuration
[env]
ENV_MODE = "production"
PYTHONPATH = "/app"
WORKERS = "8"
REDIS_HOST = "localhost"
REDIS_PORT = "6379"
REDIS_SSL = "false"
API_KEY_SECRET = "railway-production-secret-key-2024"
MCP_CREDENTIAL_ENCRYPTION_KEY = "railway-mcp-encryption-key-2024"